### PR TITLE
Feature/decoupled

### PR DESCRIPTION
**Pull request by ceneva**

### CODE REVIEW

**Comment by Polleke007** [comment]
Is it correct that the 2grid system missing data input?

**Comment by Polleke007** [comment]
For now I have added the feature & expert components, if this component should be dynamic should we loop it through the component resolver again so it can map to the right components or did you had another solution in mind?

**Comment by ceneva** [comment]
> For now I have added the feature & expert components, if this component should be dynamic should we loop through the component resolver again so it can map the right components or did you had another solution in mind?

Not immediately, but I would be careful with such things that we might not create infinite loops accidentally :). But I guess it can be done, by reusing the component resolver. Maybe you should check with Jan how important it is that the 2-grid can be used for other components too, however styling should be checked for each component that is allowed to be added to the 2-grid, since the 50% width potentially might cause problems and requires additional styling to fix this particular combination.

**Comment by Polleke007** [comment]
I have discussed this with Jan and this is ok for now, we are making the 2grid system dynamic in a separate ticket

**Pull request merged**
